baseURL = "https://fintprosjektet.github.io"
languageCode = "en-us"
title = "FINTprosjektet technical docs"
theme = "hugo-theme-bootie-docs"
contentdir = "content"
publishdir = "public"

[params]
  highlightStyle = "github"
  noCategoryLink = "true"
  description = "This is the technical documentation site for the FINT project."

[[menu.main]]
  name   = "Adapter"
  url    = "/adapter"
  weight = 10

[[menu.main]]
  name   = "Api"
  url    = "/api"
  weight = 20
[[menu.main]]
  name   = "Javadocs/.Net"
  url    = "https://docs.felleskomponent.no"
  weight = 30
[[menu.main]]
  name   = "Information models"
  url    = "https://informasjonsmodell.felleskomponent.no"
  weight = 40