baseURL = "https://fintprosjektet.github.io/docs"
languageCode = "en-us"
title = "FINTprosjektet"
theme = "hugo-material-docs"

[params]
  logo = "/images/logo.jpg"

[[menu.main]]
  name   = "Introduction"
  url    = "/introduction"
  weight = 10
  pre    = ""

[[menu.main]]
  name   = "API"
  identifier = "api"
  weight = 0
  pre    = ""

[[menu.main]]
  name   = "Overview"
  url    = "/api/overview"
  parent = "api"
  weight = 1
  pre    = ""

[[menu.main]]
  name   = "Personal"
  url    = "/api/personal"
  parent = "api"
  weight = 0
  pre    = ""

[[menu.main]]
  name   = "Organisation"
  url    = "/api/organisation"
  parent = "api"
  weight = 0
  pre    = ""

[[menu.main]]
  name   = "Code list"
  url    = "/api/codelist"
  parent = "api"
  weight = 0
  pre    = ""